# Large improvement
CUDA_VISIBLES_DEVICES=0,1,2 python -m torch.distributed.launch --nproc_per_node 3 main.py  --cfg configs/kinetics400/adamw_video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/save_ckpt_51_epochs_FullK400 --accumulation-steps 0 --opts TEST.CROP True TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_k400_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

CUDA_VISIBLES_DEVICES=0,1,2 python -m torch.distributed.launch --nproc_per_node 3 main.py  --cfg configs/kinetics400/adamw_video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/save_ckpt_100_epochs --accumulation-steps 0 --opts TEST.CROP True TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_tiny_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

CUDA_VISIBLES_DEVICES=0,1,2 python -m torch.distributed.launch --nproc_per_node 3 main.py  --cfg configs/kinetics400/adamw_video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/save_ckpt_accStep2 --accumulation-steps 0 --opts TEST.CROP True TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_tiny_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

CUDA_VISIBLES_DEVICES=0,1,2 python -m torch.distributed.launch --nproc_per_node 3 main.py  --cfg configs/kinetics400/pretraining_video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/K400-tinyVideofocalnetAdamwTub1_8batchGpu51Epochs_square_5e5Lr_warmupEpoch25_decay5e4 --accumulation-steps 0 --opts MODEL.DROP_PATH_RATE 0.3 TRAIN.WEIGHT_DECAY 5e-3 TEST.CROP True TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_tiny_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

CUDA_VISIBLES_DEVICES=0,1,2 python -m torch.distributed.launch --nproc_per_node 3 main.py  --cfg configs/kinetics400/pretraining_video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/K400-tinyVideofocalnetAdamwTub1_8batchGpu51Epochs_square_1e3Lr --accumulation-steps 0 --opts TEST.CROP True TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_tiny_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

CUDA_VISIBLES_DEVICES=0,1,2 python -m torch.distributed.launch --nproc_per_node 3 main.py  --cfg configs/kinetics400/pretraining_video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/K400-tinyVideofocalnetAdamwTub1_8batchGpu51Epochs_square_05e3Lr --accumulation-steps 0 --opts TEST.CROP True TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_tiny_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

CUDA_VISIBLES_DEVICES=0,1,2 python -m torch.distributed.launch --nproc_per_node 3 main.py  --cfg configs/kinetics400/finetuning_video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/K400-tinyVideofocalnetAdamwTub1_8batchGpu51EpochsBatch24_square_Lr --accumulation-steps 0 --opts TEST.CROP True TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_tiny_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

CUDA_VISIBLES_DEVICES=0,1,2 python -m torch.distributed.launch --nproc_per_node 3 main.py  --cfg configs/kinetics400/adamw_batch_8_video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/K400-tinyVideofocalnetAdamwTub1_8batchGpu51EpochsBatch24 --accumulation-steps 0 --opts TEST.CROP True TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_tiny_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

CUDA_VISIBLES_DEVICES=0,1,2 python -m torch.distributed.launch --nproc_per_node 3 main.py  --cfg configs/kinetics400/adamw_video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/K400-tinyVideofocalnetAdamwTub1_16batchGpu51EpochsBatch64 --accumulation-steps 0 --opts TEST.CROP True TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_tiny_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

#Full K400 training
# Videofocalvit
CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 main.py  --cfg configs/kinetics400/video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/checkpointsK400VideofocalvitTub1_8frames120EpochsBatch512 --accumulation-steps 16 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_k400_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

# videofocalnet
CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 main.py  --cfg configs/kinetics400/video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/checkpointsK400VideofocalnetTub1_8frames120EpochsBatch512 --accumulation-steps 16 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_k400_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

# 16 frames , 8 acc step
CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 main.py  --cfg configs/kinetics400/video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/checkpointsK400-tinyVideofocalnetAdamwTub1_16frames51EpochsBatch512 --accumulation-steps 8 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_tiny_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

# Evaluation on Taylor7, videofocalnet on 4 GPU
# with best K400 , 16 batch per GPU
CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4  main.py  --eval --cfg configs/kinetics400/video-focalnet_base.yaml --accumulation-steps 8 --resume /home/ens/Knguetche/Video-FocalNets/video-focalnet_base_kinetics400.pth --opts DATA.NUM_FRAMES 8 DATA.BATCH_SIZE 8 TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_k400_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

# New K400 
CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4  main.py  --eval --cfg configs/kinetics400/video-focalnet_base.yaml --accumulation-steps 16 --resume /home/ens/Knguetche/Video-FocalNets/video-focalnet_base_kinetics400.pth --opts DATA.NUM_FRAMES 8 DATA.BATCH_SIZE 8 TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_k400_f.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_f.csv

# New K400 , without Acc Step
CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 --master_port=29502  main.py  --eval --cfg configs/kinetics400/video-focalnet_base.yaml --accumulation-steps 0 --resume /home/ens/Knguetche/Video-FocalNets/video-focalnet_base_kinetics400.pth --opts DATA.NUM_FRAMES 8 DATA.BATCH_SIZE 8 TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_k400_f.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_f.csv

#without accumulation step
CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4  main.py  --eval --cfg configs/kinetics400/video-focalnet_base.yaml --resume /home/ens/Knguetche/Video-FocalNets/video-focalnet_base_kinetics400.pth --opts DATA.NUM_FRAMES 8 DATA.BATCH_SIZE 8 TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_k400_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 main.py  --cfg configs/kinetics400/video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/checkpointsK400-tinyVideofocalnetAdamwTub1_8frames51EpochsBatch512 --accumulation-steps 16 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_tiny_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 main.py  --cfg configs/kinetics400/video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/checkpointsK400-tinyVideofocalvitNoCFGTub1_8frames120EpochsBatch512 --accumulation-steps 16 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_tiny_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

# Writting error : below (down) should be tinyVideofocalvitAdamwTub1_8frames51EpochsBatch512
CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 main.py  --cfg configs/kinetics400/video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/checkpointsK400-tinyVideofocalvitAdamwTub1_8frames120EpochsBatch512 --accumulation-steps 16 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_tiny_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 main.py  --cfg configs/kinetics400/video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/checkpointsK400-tinyVideofocalvitTub1_8frames120EpochsBatch512 --accumulation-steps 16 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_tiny_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

# Tubelet at 4 (32 frames)
CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 main.py  --cfg configs/kinetics400/video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/checkpointsK400-tinyVideofocalvitTub4_32frames120EpochsBatch512 --accumulation-steps 16 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_tiny_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

# Tubelet at 2 (16 frames)
CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 main.py  --cfg configs/kinetics400/video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/checkpointsK400-tinyVideofocalvit120EpochsBatch512 --accumulation-steps 16 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_tiny_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 main.py  --cfg configs/kinetics400/video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/checkpointsK400Videofocalnet120EpochsBatch512 --resume /home/ens/Knguetche/Video-FocalNets/focalnet_base_srf.pth --accumulation-steps 16 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_k400_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 main.py  --cfg configs/kinetics400/video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/checkpointsK400VideoFocalNet16AccStep --resume /home/ens/Knguetche/Video-FocalNets/focalnet_base_srf.pth --accumulation-steps 16 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/s_update_train_kinetics400.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 main.py  --cfg configs/kinetics400/video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/checkpointsK400_adam-tinyVideofocalnet51Epochs --resume /home/ens/Knguetche/Video-FocalNets/focalnet_base_srf.pth --resume /home/ens/Knguetche/Video-FocalNets/focalnet_base_srf.pth --accumulation-steps 2 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_tiny_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 main.py  --cfg configs/kinetics400/video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/checkpointsK400-tinyVideofocalnet120EpochsBatch512 --resume /home/ens/Knguetche/Video-FocalNets/focalnet_base_srf.pth --accumulation-steps 16 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_tiny_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 main.py  --cfg configs/kinetics400/video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/checkpointsK400FullWindowsSgdLr64FpnFocalViT2AccStep__fpnFocalVit --resume /home/ens/Knguetche/Video-FocalNets/focalnet_base_srf.pth --accumulation-steps 2 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_tiny_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 main.py  --cfg configs/kinetics400/video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/checkpointsKinetics400SgdLr64FpnFocalViT2AccStep__fpnFocalVit --resume /home/ens/Knguetche/Video-FocalNets/focalnet_base_srf.pth --accumulation-steps 2 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_tiny_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 main.py  --cfg configs/kinetics400/video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/checkpointsK400FullWindowsAdamLr64FpnFocalViT2AccStep__fpnFocalVit --resume /home/ens/Knguetche/Video-FocalNets/focalnet_base_srf.pth --accumulation-steps 2 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_tiny_s.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_k400_s.csv

#CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 main.py  --cfg configs/kinetics400/video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/checkpointsKinetics400AdamLr64FpnFocalViT2AccStep__fpnFocalVit --accumulation-steps 2 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/s_train_tiny.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/s_val_kinetics400.csv

#CUDA_VISIBLES_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 main.py  --cfg configs/kinetics400/video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/checkpointsKinetics400Test2FpnFocalViT16AccStep__fpnFocalVit --accumulation-steps 4 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/train_kinetics400.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/val_kinetics400.csv

#CUDA_VISIBLES_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node 2 main.py  --cfg configs/hmdb51/video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/checkpoints_adamwlr64_hmdb51_fpnFocalVit --accumulation-steps 4 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/s_train_hmdb51.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/s_val_hmdb51.csv

#CUDA_VISIBLES_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node 2 --master_port=29508 --use_env main.py  --cfg configs/hmdb51/before_feb_18_video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/checkpoints_NoSgD_hmdb51_fpnFocalVit --accumulation-steps 4 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/s_train_hmdb51.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/s_val_hmdb51.csv

# Test with torch compile
#CUDA_VISIBLES_DEVICES=3 python -m torch.distributed.launch --nproc_per_node 1 --master_port=29501  main.py  --cfg configs/hmdb51/video-focalnet_base.yaml --output /home/ens/Knguetche/Video-FocalNets/save_checkpoints_withCompile --accumulation-steps 0 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /home/ens/Knguetche/Video-FocalNets/datasets/s_train_hmdb51.csv DATA.VAL_FILE /home/ens/Knguetche/Video-FocalNets/datasets/s_val_hmdb51.csv

# old on bools
#CUDA_VISIBLES_DEVICES=1,2 python -m torch.distributed.launch --nproc_per_node 2 --master_port=29501  main.py  --cfg configs/kinetics400/video-focalnet_base.yaml --output /projets/Knguetche/Video-FocalNets/save_checkpoints_kinetics400_fpnFocalVit --accumulation-steps 4 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE /export/datasets/public/action_recognition/kinetics_resized/k400/annotations/train.csv DATA.VAL_FILE /export/datasets/public/action_recognition/kinetics_resized/k400/annotations/val.csv

#CUDA_VISIBLES_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node 2 --master_port=29501  main.py  --cfg configs/hmdb51/video-focalnet_base.yaml --output /projets/Knguetche/Video-FocalNets/save_checkpoint_baselineTub2 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.ROOT /export/datasets/public/action_recognition/hmdb_all/ DATA.TRAIN_FILE datasets/train_hmdb51.csv DATA.VAL_FILE datasets/val_hmdb51.csv

#CUDA_VISIBLES_DEVICES=2 python -m torch.distributed.launch --nproc_per_node 1 --master_port=29501  main.py  --cfg configs/hmdb51/video-focalnet_base.yaml --output /projets/Knguetche/Video-FocalNets/save_checkpoint_lineartub1videofocalvitModel1 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.ROOT /export/datasets/public/action_recognition/hmdb_all/ DATA.TRAIN_FILE datasets/train_hmdb51.csv DATA.VAL_FILE datasets/val_hmdb51.csv

#CUDA_VISIBLES_DEVICES=1,2 python -m torch.distributed.launch --nproc_per_node 2 --master_port=29501  main.py  --cfg configs/hmdb51/video-focalnet_base.yaml --output /projets/Knguetche/Video-FocalNets/save_checkpoint_tub1videofocalvitModel1 --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.ROOT /export/datasets/public/action_recognition/hmdb_all/ DATA.TRAIN_FILE datasets/train_hmdb51.csv DATA.VAL_FILE datasets/val_hmdb51.csv

#CUDA_VISIBLES_DEVICES=2 python get_flops.py
# I think the state of the art training :
# CUDA_VISIBLES_DEVICES=1 python -m torch.distributed.launch --nproc_per_node 2  --master_port=29501 main.py  --eval --cfg configs/hmdb51/video-focalnet_base.yaml --resume './video-focalnet_base_kinetics400.pth' --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.ROOT /export/datasets/public/action_recognition/hmdb_all/ DATA.TRAIN_FILE datasets/test_hmdb51.csv DATA.VAL_FILE datasets/test_hmdb51.csv

#CUDA_VISIBLES_DEVICES=1 python -m torch.distributed.launch --nproc_per_node 2 --master_port=29501  main.py  --cfg configs/hmdb51/videoinceptionnext.yaml --output /projets/Knguetche/incepHmdb51Result1 --resume './inceptionnext_base_384.pth' --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.ROOT /export/datasets/public/action_recognition/hmdb_all/ DATA.TRAIN_FILE datasets/test_hmdb51.csv DATA.VAL_FILE datasets/test_hmdb51.csv

#CUDA_VISIBLE_DEVICES=1 torchrun --nproc_per_node=2 --master_port=29501 --rdzv_id=my_run_id --rdzv_backend=c10d main.py --cfg configs/hmdb51/videoinceptionnext.yaml --output /projets/Knguetche/incepHmdb51Result1 --resume './inceptionnext_base_384.pth' --opts TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.ROOT /export/datasets/public/action_recognition/hmdb_all/ DATA.TRAIN_FILE datasets/train_hmdb51.csv DATA.VAL_FILE datasets/val_hmdb51.csv

# python -m torch.distributed.launch --nproc_per_node 1 main.py --cfg configs/hmdb51/video-focalnet_base.yaml --resume 'ckpt/kinetics400/video-focalnet_base_kinetics400.pth' --opts DATA.TRAIN_FILE data/hmdb51/train.csv DATA.VAL_FILE data/hmdb51/val.csv
#python -m torch.distributed.launch --nproc_per_node 1 main.py --eval --cfg configs/hmdb51/video-focalnet_base.yaml --resume 'ckpt/hmdb51/video_hmdb_51.pth' --opts  DATA.NUM_FRAMES 8 DATA.BATCH_SIZE 8 TEST.NUM_CLIP 4 TEST.NUM_CROP 3 DATA.TRAIN_FILE data/hmdb51/train.csv DATA.VAL_FILE data/hmdb51/val.csv 

